### ISSUE TITLE
reactivity failing when mounting app as route on starlette_app

### ISSUE THREAD

**Issue by jamieRowen** [rstudio/py-shiny#279]
Attached is a small reproducible example. The issue I am facing is a shiny app that is defined, runs as expected as standalone. 
But when I mount the app as a route in a starlette app, the render function does not appear to trigger.

[mount_issue.zip](https://github.com/rstudio/py-shiny/files/9207825/mount_issue.zip)

with source attached to reproduce:

```
unzip mount_issue.zip
virtualenv .venv
source .venv/bin/activate
pip install -r requirements.txt
# works as expected
uvicorn issue:app_shiny
# no plot appears
uvicorn issue:star_app
```

**Comment by jcheng5** [comment]
Thanks for the report! I ran this under a debugger and found that reactivity is working, but the output that's generated is never flushed to the client. This is because the Shiny app's Starlette application's lifespan is not being invoked, and that's where reactivity and output flushing are hooked up. I'm not sure how this is supposed to work in Starlette, will need to look into their source code to see how nested applications' lifespan can get invoked.

@machow Didn't you have an example of this working last week?

**Comment by jamieRowen** [comment]
Thanks for the prompt response, I guess this is in some sense a work around for the specific problem raised in the attached zip. If I understand correctly however if I had 2 distinct shiny apps mounted side by side this would no longer be a workaround.

**Comment by jcheng5** [comment]
Yeah, in that case you'd have to write your own lifespan function that invokes the other ones. Clearly not optimal.

**Comment by machow** [comment]
This was what I wrote for starlette routes, but it doesn't involve reactivity (just a static ui), so looks like it needs to be updated (maybe with a disclaimer that it works but is not what the final approach will be here!)

https://shiny.rstudio.com/py/docs/workflow-server.html#adding-routes
