### ISSUE TITLE
Does py_Shiny work with Plotly plot?

### ISSUE THREAD

**Issue by IvanLiuTW** [rstudio/py-shiny#311]
Hi, there

Before I address my problem, I have to say **_Shiny for Python_** is awesome! The input functions are extremely useful to me that I can make my whole display more interactive. I really appreciate your hard work to make Shiny work with Python.

I have noticed that R Shiny is able to work with Plotly plots. However, when I tried to show Plotly plots using Shiny for Python, error occurred.

The error message is as follows:

> Exception: @render.plot doesn't know to render objects of type '<class 'plotly.graph_objs._figurewidget.FigureWidget'>'. Consider either requesting support for this type of plot object, and/or  explictly saving the object to a (png) file and using @render.image.

Does the error mean that Shiny for Python currently doesn't work with Plotly plot? Is there anyway I can fix this?

**Comment by wch** [comment]
Plotly can already be used with Shiny for Python, although instead of using `@render.plot`, you'll need to use the shinywidgets package.

[Example on shinylive](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMASxlWICcyACCAV3uxagGc3UAHQgAzRsRgteAawA2cKIwgZZNCAsYB9GMQAmcWSzoNmLADJqNAJTgBzRnF68apYcLESpACzXdjTVgAqd3FJXh8IbAB3Gl1bODJ+f1NidjJUNM0YuIS8FgdbGl4KLWz4smFk1lRZYjJZbAx7NC9NYgAjACt+PhZbYjcIAGIWAHFKOEYoCikJOBZdaageCF0WERpWZdV1RXy7BycXCGEIFgBeFgBGAAY7m+FF1kuITCnViQwrKA+YAGUyNM4AAKG4ASgwMHYsjINAAbooaEDNBAmDAoLJgcAbnkbgBdPLAYFXXEYACsYLyoPJeSuYIJbAhABVhAAPC4LabYvHCbiXJ7AK480SbDkWXaMGz2RzOUjAiEbMjA1kYQ5eNAggC0JOulM5ZEFeLBbPssQ5rxUal4qCghBBxUUZHOMDUyr1xWIqGdUFZbryHBg5wAzODBmhUJp2DQOVGsFB4poRLIo7pgcIWBmWLG1BkyJpCF44IRpO1iL7BGBwsQoonNhW8hW-l5q+tNhQ1js4PWWAjk3BzkzGOw4JT05nUulMmUEmnK4RpiUanUK6OIMaThv9CIpJM4ZNgTm0nkJ7m8rwZccwYhBpmpPOyIvas8+sQMAAxGi2dgOADqsXKaZnLemZPFA5zAGOwHAf0GB-PeJS2JikFQShrLnKyeDIShwHYOc2CYUB2FQTo+jnBW6KMNIky8PWWFERmFFUYw5y6DQhBKiQtTMRWjC2O0UCgriQksDcGA3BS3bOAAXv2FIEfRGargpL6wfBkyIYBym3mhrKmro8laRmuGKhgaglHaqB5iwADUrZkBgJBwCImjciwgQsLpjCxAZhkkf2FadjR+B0fRnYsWxHHEFxZFgA4ujdtkZBeOcABMSkKelUEEiFLCyFA2ATucIAVlWUTyPEqwVogLBvhi54AL4+Sw67IQURQlFk-4ziVamMEuFT4HeC6TP1LWESwAACDi2rCe4YAAoiIIhFhU41biwmjyte423rwvX9RgoGGhgcJFDQ7TyByh72aVtZKmNwjhhyACC6DAuGkY0Geu6TGCYCNeA0DwNQDgAI5Rg48DkLwGBkKyZD4EQpAUFQyDhL4wjo5E06JJUOA4zREABjgwg2qsfCk0+DT-XiQA)


Same example code in the py-shinywidgets repo here:
https://github.com/rstudio/py-shinywidgets/tree/main/examples/plotly

Please let us know if this works for your application!

**Comment by jcheng5** [comment]
+1 to what @wch said, but also, I think we should look seriously at whether it also makes sense to support Plotly plots (and other HTML/JS plotting libraries) as regular outputs, whether through `@render.plot` or a different render function.

**Comment by IvanLiuTW** [comment]
Hello Winston and Joe,

Thanks for the reply the information you provided. I will try and see if I can sort it out. 

Thank you!

**Comment by IvanLiuTW** [comment]
Hi Winston and Joe,

I modified the example code, tried a couple of times, and finally it worked! 

Thanks again for your help! 🙂

**Comment by IvanLiuTW** [comment]
Hello Winston and Joe,

Sorry, another question. I watched Winston's Py Shiny guide video and found that by just sharing the URL, the other people can interact with the same plot even they don't have the data of the plot. This is amazing. I did a small experiment by opening the URL with the Chrome app on my mobile, and it worked! 

I am not that familiar with how it works, but I assumed that the URL can directed other people to your server and run the code as well as access the same result.

Since I built the Py Shiny app on my own, so is it possible for me to make it show on a mobile browser app through the URL?
