### ISSUE TITLE
could we get support for plotly.express

### ISSUE THREAD

**Issue by mattrichard-datascience** [rstudio/py-shiny#371]
When I try using 

import plotly.express as px

I get the following error message:
@render.plot doesn't know to render objects of type '<class 'plotly.graph_objs._figure.Figure'>'. Consider either requesting support for this type of plot object, and/or  explictly saving the object to a (png) file and using @render.image.

**Comment by cpsievert** [comment]
Since https://github.com/rstudio/py-shinywidgets supports any ipywidget, you can render plotly's `FigureWidget` like this https://github.com/rstudio/py-shinywidgets/blob/main/examples/plotly/app.py

If you want to use plotly.express, you can use it to create the initial figure payload, then feed that into `FigureWidget`, sort of like this https://github.com/rstudio/py-shinywidgets/blob/c2588c4c974f0f6840ab184a526af0697f4a8919/examples/superzip/app.py#L116-L162
