### ISSUE TITLE
When removing input UI instances with `remove_ui`, the associated input value stays the same as the last input.

### ISSUE THREAD

**Issue by OksanaBash** [rstudio/py-shiny#399]
Hi, I have noticed that removing the input UI element doesn't lead to any updates in the associated input value. It is still set and equals the last input value. 

I am not sure whether it is intended to be this way or not, but maybe worth mentioning in the documentation? 

And together with this, is there any way to check whether the corresponding UI element was removed or not? Apart from the workaround of setting the tracking `reactive.Value`.

**Comment by GShotwell** [comment]
Hi Oksana, 

Can you provide a bit more context, or maybe an example of what the app does. 

One option is to use the `shiny.ui.update.*` functions, the same observer which changes the UI rendering can update the UI elements. I'm not sure that's exactly the issue here, but it's a handy pattern.

**Comment by wch** [comment]
@OksanaBash That is the expected behavior -- removing an input from the web page does not cause the input value to be unset on the server side.

One thing you could do is add a `reactive.Value()` in the server function which represents whether or not the input has been added, and set the value in the same place where you call `insert_ui()` and `remove_ui()`. In the example below, `n_exists()` represents whether or not the slider `n` is on the page.


```py
from shiny import App, reactive, render, ui


app_ui = ui.page_fluid(
    {"id": "main-content"},
    ui.input_action_button("btn", "Trigger insert/remove ui"),
    ui.output_text_verbatim("txt", placeholder=True),
    ui.output_ui("dyn_ui"),
)


def server(input, output, session):
    n_exists = reactive.Value(False)

    @output
    @render.text
    def txt():
        if n_exists():
            return f"The value of input.n() is: {input.n()}"
        else:
            return f"input.n does not exist"

    @reactive.Effect
    def _():
        btn = input.btn()
        if btn % 2 == 1:
            n_exists.set(True)
            slider = ui.input_slider(
                "n", "This slider is inserted with ui.insert_ui()", 0, 100, 20
            )
            ui.insert_ui(
                ui.div({"id": "inserted-slider"}, slider),
                selector="#main-content",
                where="beforeEnd",
            )
        elif btn > 0:
            n_exists.set(False)
            ui.remove_ui("#inserted-slider")


app = App(app_ui, server)
```

[Live example here](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6cKITIcAbnAlSIAEzh0JAVw4AdCPv1pUAfR1MAvEx1YoAczgmaAGx2qAFPqbemIXWA5Vf0QmfxgoLgBaEnJKMn8AXzwvHxsuVC0yExk5UhMAI0yyUk8wfLIDfFCwABU6DjsHOl4IFg0yAHopGGJFaz0wAEpkiB9+jGJMjKyKAA8sxTp8qDkYUrJ5-wlUZxk4NmJndToLOq04YZTvG0myabMOUtVsCAf-S4hBwwM1OBpWDSLdzpTISW7TCRtFgsDikQaIK5MV5wWYcFhkFiWSTSWQKOAYABqUFccHcADFiW0vj8xgABcGZRG0lTHDBzeKjHzqf4bMjueGIsYcf7I1Holj8hGcsYy7FkLR0UY0fw1NhwJjyYnnJjEf4gsgYCD83gsEIgfWG-kJfyCnxwZxtKWy2VSeWKpjKgIQaaGpiqYhwTEQYjCFFo+Jgb50qQ5PEYACiNBocFkiO5TBMktt3nKoysFtz-OzvH+uaYAFImAAmSxWACMTudY1F4ZYGDafLOF2LYxYzkCGixaW9mRMfYHdE80qbMv8lQkKs4mPHxxNLTaQjgqiYAHcOGQ2OMuBusjoi1UAAwSOsXq-Vi89nzUmepDgYY-tB5Tl+ymyqBTuH4ARBEg1QfpuqiRCuGiJJC-bHB8P4ym0zgpsUJz+AAxOEUQxBQ5BbI+so7mqUgWP4+R-IIcDxmohHTk2z7OvawpMGWAB8TAXo2L4tuK7ZwHyFIOt2DHOjY3S9I4Z5YeBFCQdBdDvN8RjoFiYioO4xgPJCgIaNSYAJAAukAA)


Note that you could do something similar if you are using `@render.ui` instead of `insert.ui`.
