### ISSUE TITLE
Scanpy umap plot opens a pop-up

### ISSUE THREAD

**Issue by GirayEryilmaz** [rstudio/py-shiny#406]
When I run the [example](https://shinylive.io/py/examples/#app-with-plot), everything worked fine but when I used scanpy to make a plot, it showed in a new window as an interactive figure.

I had to add these lines on top to make the figure appear in the browser:

import matplotlib
matplotlib.use('Agg')

Maybe pyshiny should "force" a backend?

**Comment by jcheng5** [comment]
Thanks for the report! Do you mind providing a scanpy snippet that repros this?

**Comment by GirayEryilmaz** [comment]
Sure, here is the most basic example I have:

```python
from shiny import App, render, ui
import scanpy as sc

app_ui = ui.page_fluid(
    ui.output_plot("umap")
)

def server(input, output, session):

    adata = sc.datasets.pbmc3k_processed()

    @output
    @render.plot(alt="A umap")
    def umap():
        genes_list = ['CD8A', 'CD8B']
        sc.pl.umap(adata, color = genes_list)

app = App(app_ui, server, debug=False)
```

**Comment by wch** [comment]
It looks like this is caused by scanpy's `autoshow` setting, which calls `.show()` on figure objects by default. (My guess is that if you use the Agg backend, it can't show to a popup window.) If you disable `autoshow` like this, the app should work as expected, without using `Agg`:

```py
import scanpy as sc
sc.settings.autoshow = False
```

https://scanpy.readthedocs.io/en/stable/generated/scanpy._settings.ScanpyConfig.autoshow.html

**Comment by GirayEryilmaz** [comment]
Yes! This worked for me, thanks.
