### ISSUE TITLE
Clarify use of global variables

### ISSUE THREAD

**Issue by hedsnz** [rstudio/py-shiny#469]
Is there a recommended approach to setting global variables that can be used a) in the application code and b) as parameters to `run_app`?

In R, we would typically set up global variables/options in `R/global.R`, e.g.,

```
# R/global.R
options(shiny.host = "0.0.0.0", shiny.port = "8888")
```

When `shiny::runApp` is called, `R/global.R` is sourced automatically, and the app is therefore served at port 8888.

In Python, the closest equivalent design that I can figure out is to create files for global variables and for calling `run_app`, e.g.,

```
# globals.py
port = 8888
app_title = "Hello world"
```

```
# app.py
from shiny import App, ui
from globals import app_title
app_ui = ui.page_fluid(ui.h1(app_title))
app = App(app_ui, None)
```

```
# run.py
from shiny import run_app
from globals import port
run_app(port=port)
```

```
# bash
python run.py
```

Is this an appropriate architecture for defining global variables/options to pass to py-shiny apps? Is there a better way, and if so, is that documented anywhere? Thanks!

**Comment by jcheng5** [comment]
Interesting... the original reason for globals.R in Shiny for R was to make variables available in both ui.R and server.R. After we introduced the single-file app.R option, most people preferred that and stopped using global.R, as there wasn't really a reason to have a separate file rather than putting variables at the top of app.R. (It's interesting that the shiny.host and shiny.port options can be set there and take effect--that is one advantage over app.R)

In answer to your question, no, there's not an equivalent in Python. You could do something like you've done here, but I'm not totally sure why you would; for the port, I'd hardcode that in run.py rather than hardcoding it in a separate global.py.

Is there a specific reason besides that, that's motivating this question?

**Comment by hedsnz** [comment]
Thanks for the quick response! Yeah, that makes sense. I prefer the `app.R` + modules + `global.R` approach, as I often end up with quite a few global variables/constants that would otherwise make `app.R` quite lengthy. I quite like having an `app.R` that basically says, "this is how the app is laid out at a very high level; all the detail is in the R folder with `global.R` and the modules."

The motivation for the question was just that I was looking for an equivalent to R's `options(shiny.host = ..., ...)` in Python -- some way to define the `host` and `port` values outside of the `run_app` CLI, such that I can avoid typing `shiny run --reload --port xxxx --host "x.x.x.x" app/app.py` if I need to run it with specific host/port values. So, this `run.py` solution (and I agree with your comment about simply putting host/port values there, instead of a `globals.py`) was based off https://shiny.rstudio.com/py/api/run_app.html -- and I just wanted to make sure that there wasn't some other way of doing it that I had missed.

I'm not sure whether this would be a common enough pattern to make it worth documenting in https://shiny.rstudio.com/py/docs/running-debugging.html though.

**Comment by jcheng5** [comment]
OK, thanks for the clarification. I think we'll leave it as-is unless we get more feedback that there is confusion about this. Thanks!
