### ISSUE TITLE
Rename `x.ui.accordion_panel_update()` to `x.ui.update_accordion_panel()`

### ISSUE THREAD

**Issue by schloerke** [rstudio/py-shiny#628]
This follows pattern of `ui.update_*()` which is currently implemented in `ui`.

**Comment by cpsievert** [comment]
FWIW, @gadenbuie and I were discussing this recently and I think we had agreed that things like accordions, navsets, sidebars, that are kind of inputs, but are different enough, shouldn't necessarily follow the `update_*()` pattern (especially when there are multiple `noun_verb()` actions). That said, I don't think we'd be opposed to there being aliases for these cases

**Comment by schloerke** [comment]
Ok. I'll leave as is. Just wanted to make sure there was reasoning behind it.

--------------------------

@cpsievert Keep `update_tooltip()` as is? (And not change to `tooltip_update()`.... as it's a layout and not primarily an input.)

**Comment by cpsievert** [comment]
> Keep `update_tooltip()` as is? 

Yea, I think so. The reasoning for this that, if the updating API is small/simple (e.g., it's just `update_*()` and/or `toggle_*()`), then we'll commit to those as a prefix (since we'll have many of them). But, if the API is more complex, we'll gravitate towards `noun_verb()`. That said, at least for `update` and `toggle`, I think it's fine if we have an alias so that either way works (i.e., I'd be fine if  `update_accordion_panel()` was added as an alias, but let's not remove `accordion_panel_update()`)

**Comment by schloerke** [comment]
Fixed in #559
